---
# tasks file for sshd
- name: user
  block:
    - name: sshd_config
      template:
        src: sshd_config.j2
        dest: "{{ sshd_path }}"
        mode: 0644
      register: config_status

    - name: reload sshd Ubuntu
      service:
        name: sshd
        state: reloaded
      when: config_status.changed and ansible_distribution == 'Ubuntu'

    - name: reload sshd RedHat
      systemd:
        name: sshd.service
        state: reloaded
      when: config_status.changed and ansible_os_family == 'RedHat'
  when: inventory_hostname not in groups.NFERX
