---
# tasks file for sshd
- name: sshd_config
  template:
    src: sshd_config.j2
    dest: "{{ sshd_path }}"
    mode: 0644
  register: config_status

- name: reload sshd
  service:
    name: sshd
    state: reloaded
  when: config_status.changed and ansible_distribution != 'MacOSX'
